// GENERATED FILE -- do not edit by hand.
// Regenerate: node scripts/gen-framework-section-text.mjs
//
// Short text for section and reference IDs on /compliance/[key].
//
// RIGHTS: NIST publications are works of the US federal government and carry no
// domestic copyright; NIST asks only for credit, which the compliance page
// gives in its Sources line. Frameworks whose text is licensed -- ISO 27002,
// PCI DSS, SOC 2 (AICPA), IEC 62443, CIS Controls -- are deliberately absent
// and render as bare IDs.
//
// Source: NIST Cybersecurity and Privacy Reference Tool (CPRT) JSON export
// (NIST SP 800-53 Rev. 5 = sp_800_53_5_2_0, NIST SP 800-171 Rev. 3 = sp_800_171_3_0_0).

/** NIST SP 800-53 Rev. 5 -- families, controls and control enhancements. */
const NIST_800_53: Record<string, string> = {
  "AC": "Access Control",
  "AC-01": "Policy and Procedures",
  "AC-02": "Account Management",
  "AC-02(01)": "Automated System Account Management",
  "AC-02(02)": "Automated Temporary and Emergency Account Management",
  "AC-02(03)": "Disable Accounts",
  "AC-02(04)": "Automated Audit Actions",
  "AC-02(05)": "Inactivity Logout",
  "AC-02(06)": "Dynamic Privilege Management",
  "AC-02(07)": "Privileged User Accounts",
  "AC-02(08)": "Dynamic Account Management",
  "AC-02(09)": "Restrictions on Use of Shared and Group Accounts",
  "AC-02(10)": "Shared and Group Account Credential Change",
  "AC-02(11)": "Usage Conditions",
  "AC-02(12)": "Account Monitoring for Atypical Usage",
  "AC-02(13)": "Disable Accounts for High-Risk Individuals",
  "AC-03": "Access Enforcement",
  "AC-03(01)": "Restricted Access to Privileged Functions",
  "AC-03(02)": "Dual Authorization",
  "AC-03(03)": "Mandatory Access Control",
  "AC-03(04)": "Discretionary Access Control",
  "AC-03(05)": "Security-Relevant Information",
  "AC-03(06)": "Protection of User and System Information",
  "AC-03(07)": "Role-Based Access Control",
  "AC-03(08)": "Revocation of Access Authorizations",
  "AC-03(09)": "Controlled Release",
  "AC-03(10)": "Audited Override of Access Control Mechanisms",
  "AC-03(11)": "Restrict Access to Specific Information Types",
  "AC-03(12)": "Assert and Enforce Application Access",
  "AC-03(13)": "Attribute-Based Access Control",
  "AC-03(14)": "Individual Access",
  "AC-03(15)": "Discretionary and Mandatory Access Control",
  "AC-04": "Information Flow Enforcement",
  "AC-04(01)": "Object Security and Privacy Attributes",
  "AC-04(02)": "Processing Domains",
  "AC-04(03)": "Dynamic Information Flow Control",
  "AC-04(04)": "Flow Control of Encrypted Information",
  "AC-04(05)": "Embedded Data Types",
  "AC-04(06)": "Metadata",
  "AC-04(07)": "One-Way Flow Mechanisms",
  "AC-04(08)": "Security and Privacy Policy Filters",
  "AC-04(09)": "Human Reviews",
  "AC-04(10)": "Enable and Disable Security or Privacy Policy Filters",
  "AC-04(11)": "Configuration of Security or Privacy Policy Filters",
  "AC-04(12)": "Data Type Identifiers",
  "AC-04(13)": "Decomposition Into Policy-Relevant Subcomponents",
  "AC-04(14)": "Security or Privacy Policy Filter Constraints",
  "AC-04(15)": "Detection of Unsanctioned Information",
  "AC-04(16)": "Information Transfers on Interconnected Systems",
  "AC-04(17)": "Domain Authentication",
  "AC-04(18)": "Security Attribute Binding",
  "AC-04(19)": "Validation of Metadata",
  "AC-04(20)": "Approved Solutions",
  "AC-04(21)": "Physical or Logical Separation of Information Flows",
  "AC-04(22)": "Access Only",
  "AC-04(23)": "Modify Non-Releasable Information",
  "AC-04(24)": "Internal Normalized Format",
  "AC-04(25)": "Data Sanitization",
  "AC-04(26)": "Audit Filtering Actions",
  "AC-04(27)": "Redundant/Independent Filtering Mechanisms",
  "AC-04(28)": "Linear Filter Pipelines",
  "AC-04(29)": "Filter Orchestration Engines",
  "AC-04(30)": "Filter Mechanisms Using Multiple Processes",
  "AC-04(31)": "Failed Content Transfer Prevention",
  "AC-04(32)": "Process Requirements for Information Transfer",
  "AC-05": "Separation of Duties",
  "AC-06": "Least Privilege",
  "AC-06(01)": "Authorize Access to Security Functions",
  "AC-06(02)": "Non-Privileged Access for Nonsecurity Functions",
  "AC-06(03)": "Network Access to Privileged Commands",
  "AC-06(04)": "Separate Processing Domains",
  "AC-06(05)": "Privileged Accounts",
  "AC-06(06)": "Privileged Access by Non-Organizational Users",
  "AC-06(07)": "Review of User Privileges",
  "AC-06(08)": "Privilege Levels for Code Execution",
  "AC-06(09)": "Log Use of Privileged Functions",
  "AC-06(10)": "Prohibit Non-Privileged Users from Executing Privileged Functions",
  "AC-07": "Unsuccessful Logon Attempts",
  "AC-07(01)": "Automatic Account Lock",
  "AC-07(02)": "Purge or Wipe Mobile Device",
  "AC-07(03)": "Biometric Attempt Limiting",
  "AC-07(04)": "Use of Alternate Authentication Factor",
  "AC-08": "System Use Notification",
  "AC-09": "Previous Logon Notification",
  "AC-09(01)": "Unsuccessful Logons",
  "AC-09(02)": "Successful and Unsuccessful Logons",
  "AC-09(03)": "Notification of Account Changes",
  "AC-09(04)": "Additional Logon Information",
  "AC-10": "Concurrent Session Control",
  "AC-11": "Device Lock",
  "AC-11(01)": "Pattern-Hiding Displays",
  "AC-12": "Session Termination",
  "AC-12(01)": "User-Initiated Logouts",
  "AC-12(02)": "Termination Message",
  "AC-12(03)": "Timeout Warning Message",
  "AC-13": "Supervision and Review — Access Control",
  "AC-14": "Permitted Actions Without Identification or Authentication",
  "AC-14(01)": "Necessary Uses",
  "AC-15": "Automated Marking",
  "AC-16": "Security and Privacy Attributes",
  "AC-16(01)": "Dynamic Attribute Association",
  "AC-16(02)": "Attribute Value Changes by Authorized Individuals",
  "AC-16(03)": "Maintenance of Attribute Associations by System",
  "AC-16(04)": "Association of Attributes by Authorized Individuals",
  "AC-16(05)": "Attribute Displays on Objects to Be Output",
  "AC-16(06)": "Maintenance of Attribute Association",
  "AC-16(07)": "Consistent Attribute Interpretation",
  "AC-16(08)": "Association Techniques and Technologies",
  "AC-16(09)": "Attribute Reassignment — Regrading Mechanisms",
  "AC-16(10)": "Attribute Configuration by Authorized Individuals",
  "AC-17": "Remote Access",
  "AC-17(01)": "Monitoring and Control",
  "AC-17(02)": "Protection of Confidentiality and Integrity Using Encryption",
  "AC-17(03)": "Managed Access Control Points",
  "AC-17(04)": "Privileged Commands and Access",
  "AC-17(05)": "Monitoring for Unauthorized Connections",
  "AC-17(06)": "Protection of Mechanism Information",
  "AC-17(07)": "Additional Protection for Security Function Access",
  "AC-17(08)": "Disable Nonsecure Network Protocols",
  "AC-17(09)": "Disconnect or Disable Access",
  "AC-17(10)": "Authenticate Remote Commands",
  "AC-18": "Wireless Access",
  "AC-18(01)": "Authentication and Encryption",
  "AC-18(02)": "Monitoring Unauthorized Connections",
  "AC-18(03)": "Disable Wireless Networking",
  "AC-18(04)": "Restrict Configurations by Users",
  "AC-18(05)": "Antennas and Transmission Power Levels",
  "AC-19": "Access Control for Mobile Devices",
  "AC-19(01)": "Use of Writable and Portable Storage Devices",
  "AC-19(02)": "Use of Personally Owned Portable Storage Devices",
  "AC-19(03)": "Use of Portable Storage Devices with No Identifiable Owner",
  "AC-19(04)": "Restrictions for Classified Information",
  "AC-19(05)": "Full Device or Container-Based Encryption",
  "AC-20": "Use of External Systems",
  "AC-20(01)": "Limits on Authorized Use",
  "AC-20(02)": "Portable Storage Devices — Restricted Use",
  "AC-20(03)": "Non-Organizationally Owned Systems — Restricted Use",
  "AC-20(04)": "Network Accessible Storage Devices — Prohibited Use",
  "AC-20(05)": "Portable Storage Devices — Prohibited Use",
  "AC-21": "Information Sharing",
  "AC-21(01)": "Automated Decision Support",
  "AC-21(02)": "Information Search and Retrieval",
  "AC-22": "Publicly Accessible Content",
  "AC-23": "Data Mining Protection",
  "AC-24": "Access Control Decisions",
  "AC-24(01)": "Transmit Access Authorization Information",
  "AC-24(02)": "No User or Process Identity",
  "AC-25": "Reference Monitor",
  "AT": "Awareness and Training",
  "AT-01": "Policy and Procedures",
  "AT-02": "Literacy Training and Awareness",
  "AT-02(01)": "Practical Exercises",
  "AT-02(02)": "Insider Threat",
  "AT-02(03)": "Social Engineering and Mining",
  "AT-02(04)": "Suspicious Communications and Anomalous System Behavior",
  "AT-02(05)": "Advanced Persistent Threat",
  "AT-02(06)": "Cyber Threat Environment",
  "AT-03": "Role-Based Training",
  "AT-03(01)": "Environmental Controls",
  "AT-03(02)": "Physical Security Controls",
  "AT-03(03)": "Practical Exercises",
  "AT-03(04)": "Suspicious Communications and Anomalous System Behavior",
  "AT-03(05)": "Processing Personally Identifiable Information",
  "AT-04": "Training Records",
  "AT-05": "Contacts with Security Groups and Associations",
  "AT-06": "Training Feedback",
  "AU": "Audit and Accountability",
  "AU-01": "Policy and Procedures",
  "AU-02": "Event Logging",
  "AU-02(01)": "Compilation of Audit Records from Multiple Sources",
  "AU-02(02)": "Selection of Audit Events by Component",
  "AU-02(03)": "Reviews and Updates",
  "AU-02(04)": "Privileged Functions",
  "AU-03": "Content of Audit Records",
  "AU-03(01)": "Additional Audit Information",
  "AU-03(02)": "Centralized Management of Planned Audit Record Content",
  "AU-03(03)": "Limit Personally Identifiable Information Elements",
  "AU-04": "Audit Log Storage Capacity",
  "AU-04(01)": "Transfer to Alternate Storage",
  "AU-05": "Response to Audit Logging Process Failures",
  "AU-05(01)": "Storage Capacity Warning",
  "AU-05(02)": "Real-Time Alerts",
  "AU-05(03)": "Configurable Traffic Volume Thresholds",
  "AU-05(04)": "Shutdown on Failure",
  "AU-05(05)": "Alternate Audit Logging Capability",
  "AU-06": "Audit Record Review, Analysis, and Reporting",
  "AU-06(01)": "Automated Process Integration",
  "AU-06(02)": "Automated Security Alerts",
  "AU-06(03)": "Correlate Audit Record Repositories",
  "AU-06(04)": "Central Review and Analysis",
  "AU-06(05)": "Integrated Analysis of Audit Records",
  "AU-06(06)": "Correlation with Physical Monitoring",
  "AU-06(07)": "Permitted Actions",
  "AU-06(08)": "Full Text Analysis of Privileged Commands",
  "AU-06(09)": "Correlation with Information from Nontechnical Sources",
  "AU-06(10)": "Audit Level Adjustment",
  "AU-07": "Audit Record Reduction and Report Generation",
  "AU-07(01)": "Automatic Processing",
  "AU-07(02)": "Automatic Sort and Search",
  "AU-08": "Time Stamps",
  "AU-08(01)": "Synchronization with Authoritative Time Source",
  "AU-08(02)": "Secondary Authoritative Time Source",
  "AU-09": "Protection of Audit Information",
  "AU-09(01)": "Hardware Write-Once Media",
  "AU-09(02)": "Store on Separate Physical Systems or Components",
  "AU-09(03)": "Cryptographic Protection",
  "AU-09(04)": "Access by Subset of Privileged Users",
  "AU-09(05)": "Dual Authorization",
  "AU-09(06)": "Read-Only Access",
  "AU-09(07)": "Store on Component with Different Operating System",
  "AU-10": "Non-Repudiation",
  "AU-10(01)": "Association of Identities",
  "AU-10(02)": "Validate Binding of Information Producer Identity",
  "AU-10(03)": "Chain of Custody",
  "AU-10(04)": "Validate Binding of Information Reviewer Identity",
  "AU-10(05)": "Digital Signatures",
  "AU-11": "Audit Record Retention",
  "AU-11(01)": "Long-Term Retrieval Capability",
  "AU-12": "Audit Record Generation",
  "AU-12(01)": "System-Wide and Time-Correlated Audit Trail",
  "AU-12(02)": "Standardized Formats",
  "AU-12(03)": "Changes by Authorized Individuals",
  "AU-12(04)": "Query Parameter Audits of Personally Identifiable Information",
  "AU-13": "Monitoring for Information Disclosure",
  "AU-13(01)": "Use of Automated Tools",
  "AU-13(02)": "Review of Monitored Sites",
  "AU-13(03)": "Unauthorized Replication of Information",
  "AU-14": "Session Audit",
  "AU-14(01)": "System Start-Up",
  "AU-14(02)": "Capture and Record Content",
  "AU-14(03)": "Remote Viewing and Listening",
  "AU-15": "Alternate Audit Logging Capability",
  "AU-16": "Cross-Organizational Audit Logging",
  "AU-16(01)": "Identity Preservation",
  "AU-16(02)": "Sharing of Audit Information",
  "AU-16(03)": "Disassociability",
  "CA": "Assessment, Authorization, and Monitoring",
  "CA-01": "Policy and Procedures",
  "CA-02": "Control Assessments",
  "CA-02(01)": "Independent Assessors",
  "CA-02(02)": "Specialized Assessments",
  "CA-02(03)": "Leveraging Results from External Organizations",
  "CA-03": "Information Exchange",
  "CA-03(01)": "Unclassified National Security System Connections",
  "CA-03(02)": "Classified National Security System Connections",
  "CA-03(03)": "Unclassified Non-National Security System Connections",
  "CA-03(04)": "Connections to Public Networks",
  "CA-03(05)": "Restrictions on External System Connections",
  "CA-03(06)": "Transfer Authorizations",
  "CA-03(07)": "Transitive Information Exchanges",
  "CA-04": "Security Certification",
  "CA-05": "Plan of Action and Milestones",
  "CA-05(01)": "Automation Support for Accuracy and Currency",
  "CA-06": "Authorization",
  "CA-06(01)": "Joint Authorization — Intra-Organization",
  "CA-06(02)": "Joint Authorization — Inter-Organization",
  "CA-07": "Continuous Monitoring",
  "CA-07(01)": "Independent Assessment",
  "CA-07(02)": "Types of Assessments",
  "CA-07(03)": "Trend Analyses",
  "CA-07(04)": "Risk Monitoring",
  "CA-07(05)": "Consistency Analysis",
  "CA-07(06)": "Automation Support for Monitoring",
  "CA-08": "Penetration Testing",
  "CA-08(01)": "Independent Penetration Testing Agent or Team",
  "CA-08(02)": "Red Team Exercises",
  "CA-08(03)": "Facility Penetration Testing",
  "CA-09": "Internal System Connections",
  "CA-09(01)": "Compliance Checks",
  "CM": "Configuration Management",
  "CM-01": "Policy and Procedures",
  "CM-02": "Baseline Configuration",
  "CM-02(01)": "Reviews and Updates",
  "CM-02(02)": "Automation Support for Accuracy and Currency",
  "CM-02(03)": "Retention of Previous Configurations",
  "CM-02(04)": "Unauthorized Software",
  "CM-02(05)": "Authorized Software",
  "CM-02(06)": "Development and Test Environments",
  "CM-02(07)": "Configure Systems and Components for High-Risk Areas",
  "CM-03": "Configuration Change Control",
  "CM-03(01)": "Automated Documentation, Notification, and Prohibition of Changes",
  "CM-03(02)": "Testing, Validation, and Documentation of Changes",
  "CM-03(03)": "Automated Change Implementation",
  "CM-03(04)": "Security and Privacy Representatives",
  "CM-03(05)": "Automated Security Response",
  "CM-03(06)": "Cryptography Management",
  "CM-03(07)": "Review System Changes",
  "CM-03(08)": "Prevent or Restrict Configuration Changes",
  "CM-04": "Impact Analyses",
  "CM-04(01)": "Separate Test Environments",
  "CM-04(02)": "Verification of Controls",
  "CM-05": "Access Restrictions for Change",
  "CM-05(01)": "Automated Access Enforcement and Audit Records",
  "CM-05(02)": "Review System Changes",
  "CM-05(03)": "Signed Components",
  "CM-05(04)": "Dual Authorization",
  "CM-05(05)": "Privilege Limitation for Production and Operation",
  "CM-05(06)": "Limit Library Privileges",
  "CM-05(07)": "Automatic Implementation of Security Safeguards",
  "CM-06": "Configuration Settings",
  "CM-06(01)": "Automated Management, Application, and Verification",
  "CM-06(02)": "Respond to Unauthorized Changes",
  "CM-06(03)": "Unauthorized Change Detection",
  "CM-06(04)": "Conformance Demonstration",
  "CM-07": "Least Functionality",
  "CM-07(01)": "Periodic Review",
  "CM-07(02)": "Prevent Program Execution",
  "CM-07(03)": "Registration Compliance",
  "CM-07(04)": "Unauthorized Software — Deny-by-Exception",
  "CM-07(05)": "Authorized Software — Allow-by-Exception",
  "CM-07(06)": "Confined Environments with Limited Privileges",
  "CM-07(07)": "Code Execution in Protected Environments",
  "CM-07(08)": "Binary or Machine Executable Code",
  "CM-07(09)": "Prohibiting the Use of Unauthorized Hardware",
  "CM-08": "System Component Inventory",
  "CM-08(01)": "Updates During Installation and Removal",
  "CM-08(02)": "Automated Maintenance",
  "CM-08(03)": "Automated Unauthorized Component Detection",
  "CM-08(04)": "Accountability Information",
  "CM-08(05)": "No Duplicate Accounting of Components",
  "CM-08(06)": "Assessed Configurations and Approved Deviations",
  "CM-08(07)": "Centralized Repository",
  "CM-08(08)": "Automated Location Tracking",
  "CM-08(09)": "Assignment of Components to Systems",
  "CM-09": "Configuration Management Plan",
  "CM-09(01)": "Assignment of Responsibility",
  "CM-10": "Software Usage Restrictions",
  "CM-10(01)": "Open-Source Software",
  "CM-11": "User-Installed Software",
  "CM-11(01)": "Alerts for Unauthorized Installations",
  "CM-11(02)": "Software Installation with Privileged Status",
  "CM-11(03)": "Automated Enforcement and Monitoring",
  "CM-12": "Information Location",
  "CM-12(01)": "Automated Tools to Support Information Location",
  "CM-13": "Data Action Mapping",
  "CM-14": "Signed Components",
  "CP": "Contingency Planning",
  "CP-01": "Policy and Procedures",
  "CP-02": "Contingency Plan",
  "CP-02(01)": "Coordinate with Related Plans",
  "CP-02(02)": "Capacity Planning",
  "CP-02(03)": "Resume Mission and Business Functions",
  "CP-02(04)": "Resume All Mission and Business Functions",
  "CP-02(05)": "Continue Mission and Business Functions",
  "CP-02(06)": "Alternate Processing and Storage Sites",
  "CP-02(07)": "Coordinate with External Service Providers",
  "CP-02(08)": "Identify Critical Assets",
  "CP-03": "Contingency Training",
  "CP-03(01)": "Simulated Events",
  "CP-03(02)": "Mechanisms Used in Training Environments",
  "CP-04": "Contingency Plan Testing",
  "CP-04(01)": "Coordinate with Related Plans",
  "CP-04(02)": "Alternate Processing Site",
  "CP-04(03)": "Automated Testing",
  "CP-04(04)": "Full Recovery and Reconstitution",
  "CP-04(05)": "Self-Challenge",
  "CP-05": "Contingency Plan Update",
  "CP-06": "Alternate Storage Site",
  "CP-06(01)": "Separation from Primary Site",
  "CP-06(02)": "Recovery Time and Recovery Point Objectives",
  "CP-06(03)": "Accessibility",
  "CP-07": "Alternate Processing Site",
  "CP-07(01)": "Separation from Primary Site",
  "CP-07(02)": "Accessibility",
  "CP-07(03)": "Priority of Service",
  "CP-07(04)": "Preparation for Use",
  "CP-07(05)": "Equivalent Information Security Safeguards",
  "CP-07(06)": "Inability to Return to Primary Site",
  "CP-08": "Telecommunications Services",
  "CP-08(01)": "Priority of Service Provisions",
  "CP-08(02)": "Single Points of Failure",
  "CP-08(03)": "Separation of Primary and Alternate Providers",
  "CP-08(04)": "Provider Contingency Plan",
  "CP-08(05)": "Alternate Telecommunication Service Testing",
  "CP-09": "System Backup",
  "CP-09(01)": "Testing for Reliability and Integrity",
  "CP-09(02)": "Test Restoration Using Sampling",
  "CP-09(03)": "Separate Storage for Critical Information",
  "CP-09(04)": "Protection from Unauthorized Modification",
  "CP-09(05)": "Transfer to Alternate Storage Site",
  "CP-09(06)": "Redundant Secondary System",
  "CP-09(07)": "Dual Authorization for Deletion or Destruction",
  "CP-09(08)": "Cryptographic Protection",
  "CP-10": "System Recovery and Reconstitution",
  "CP-10(01)": "Contingency Plan Testing",
  "CP-10(02)": "Transaction Recovery",
  "CP-10(03)": "Compensating Security Controls",
  "CP-10(04)": "Restore within Time Period",
  "CP-10(05)": "Failover Capability",
  "CP-10(06)": "Component Protection",
  "CP-11": "Alternate Communications Protocols",
  "CP-12": "Safe Mode",
  "CP-13": "Alternative Security Mechanisms",
  "IA": "Identification and Authentication",
  "IA-01": "Policy and Procedures",
  "IA-02": "Identification and Authentication (Organizational Users)",
  "IA-02(01)": "Multi-Factor Authentication to Privileged Accounts",
  "IA-02(02)": "Multi-Factor Authentication to Non-Privileged Accounts",
  "IA-02(03)": "Local Access to Privileged Accounts",
  "IA-02(04)": "Local Access to Non-Privileged Accounts",
  "IA-02(05)": "Individual Authentication with Group Authentication",
  "IA-02(06)": "Access to Accounts —Separate Device",
  "IA-02(07)": "Network Access to Non-Privileged Accounts — Separate Device",
  "IA-02(08)": "Access to Accounts — Replay Resistant",
  "IA-02(09)": "Network Access to Non-Privileged Accounts — Replay Resistant",
  "IA-02(10)": "Single Sign-on",
  "IA-02(11)": "Remote Access — Separate Device",
  "IA-02(12)": "Acceptance of PIV Credentials",
  "IA-02(13)": "Out-Of-Band Authentication",
  "IA-03": "Device Identification and Authentication",
  "IA-03(01)": "Cryptographic Bidirectional Authentication",
  "IA-03(02)": "Cryptographic Bidirectional Network Authentication",
  "IA-03(03)": "Dynamic Address Allocation",
  "IA-03(04)": "Device Attestation",
  "IA-04": "Identifier Management",
  "IA-04(01)": "Prohibit Account Identifiers as Public Identifiers",
  "IA-04(02)": "Supervisor Authorization",
  "IA-04(03)": "Multiple Forms of Certification",
  "IA-04(04)": "Identify User Status",
  "IA-04(05)": "Dynamic Management",
  "IA-04(06)": "Cross-Organization Management",
  "IA-04(07)": "In-Person Registration",
  "IA-04(08)": "Pairwise Pseudonymous Identifiers",
  "IA-04(09)": "Attribute Maintenance and Protection",
  "IA-05": "Authenticator Management",
  "IA-05(01)": "Password-Based Authentication",
  "IA-05(02)": "Public Key-Based Authentication",
  "IA-05(03)": "In-Person or Trusted External Party Registration",
  "IA-05(04)": "Automated Support for Password Strength Determination",
  "IA-05(05)": "Change Authenticators Prior to Delivery",
  "IA-05(06)": "Protection of Authenticators",
  "IA-05(07)": "No Embedded Unencrypted Static Authenticators",
  "IA-05(08)": "Multiple System Accounts",
  "IA-05(09)": "Federated Credential Management",
  "IA-05(10)": "Dynamic Credential Binding",
  "IA-05(11)": "Hardware Token-Based Authentication",
  "IA-05(12)": "Biometric Authentication Performance",
  "IA-05(13)": "Expiration of Cached Authenticators",
  "IA-05(14)": "Managing Content of PKI Trust Stores",
  "IA-05(15)": "GSA-Approved Products and Services",
  "IA-05(16)": "In-Person or Trusted External Party Authenticator Issuance",
  "IA-05(17)": "Presentation Attack Detection for Biometric Authenticators",
  "IA-05(18)": "Password Managers",
  "IA-06": "Authentication Feedback",
  "IA-07": "Cryptographic Module Authentication",
  "IA-08": "Identification and Authentication (Non-Organizational Users)",
  "IA-08(01)": "Acceptance of PIV Credentials from Other Agencies",
  "IA-08(02)": "Acceptance of External Authenticators",
  "IA-08(03)": "Use of FICAM-Approved Products",
  "IA-08(04)": "Use of Defined Profiles",
  "IA-08(05)": "Acceptance of PIV-I Credentials",
  "IA-08(06)": "Disassociability",
  "IA-09": "Service Identification and Authentication",
  "IA-09(01)": "Information Exchange",
  "IA-09(02)": "Transmission of Decisions",
  "IA-10": "Adaptive Authentication",
  "IA-11": "Re-Authentication",
  "IA-12": "Identity Proofing",
  "IA-12(01)": "Supervisor Authorization",
  "IA-12(02)": "Identity Evidence",
  "IA-12(03)": "Identity Evidence Validation and Verification",
  "IA-12(04)": "In-Person Validation and Verification",
  "IA-12(05)": "Address Confirmation",
  "IA-12(06)": "Accept Externally-Proofed Identities",
  "IA-13": "Identity Providers and Authorization Servers",
  "IA-13(01)": "Protection of Cryptographic Keys",
  "IA-13(02)": "Verification of Identity Assertions and Access Tokens",
  "IA-13(03)": "Token Management",
  "IR": "Incident Response",
  "IR-01": "Policy and Procedures",
  "IR-02": "Incident Response Training",
  "IR-02(01)": "Simulated Events",
  "IR-02(02)": "Automated Training Environments",
  "IR-02(03)": "Breach",
  "IR-03": "Incident Response Testing",
  "IR-03(01)": "Automated Testing",
  "IR-03(02)": "Coordination with Related Plans",
  "IR-03(03)": "Continuous Improvement",
  "IR-04": "Incident Handling",
  "IR-04(01)": "Automated Incident Handling Processes",
  "IR-04(02)": "Dynamic Reconfiguration",
  "IR-04(03)": "Continuity of Operations",
  "IR-04(04)": "Information Correlation",
  "IR-04(05)": "Automatic Disabling of System",
  "IR-04(06)": "Insider Threats",
  "IR-04(07)": "Insider Threats — Intra-Organization Coordination",
  "IR-04(08)": "Correlation with External Organizations",
  "IR-04(09)": "Dynamic Response Capability",
  "IR-04(10)": "Supply Chain Coordination",
  "IR-04(11)": "Integrated Incident Response Team",
  "IR-04(12)": "Malicious Code and Forensic Analysis",
  "IR-04(13)": "Behavior Analysis",
  "IR-04(14)": "Security Operations Center",
  "IR-04(15)": "Public Relations and Reputation Repair",
  "IR-05": "Incident Monitoring",
  "IR-05(01)": "Automated Tracking, Data Collection, and Analysis",
  "IR-06": "Incident Reporting",
  "IR-06(01)": "Automated Reporting",
  "IR-06(02)": "Vulnerabilities Related to Incidents",
  "IR-06(03)": "Supply Chain Coordination",
  "IR-07": "Incident Response Assistance",
  "IR-07(01)": "Automation Support for Availability of Information and Support",
  "IR-07(02)": "Coordination with External Providers",
  "IR-08": "Incident Response Plan",
  "IR-08(01)": "Breaches",
  "IR-09": "Information Spillage Response",
  "IR-09(01)": "Responsible Personnel",
  "IR-09(02)": "Training",
  "IR-09(03)": "Post-Spill Operations",
  "IR-09(04)": "Exposure to Unauthorized Personnel",
  "IR-10": "Integrated Information Security Analysis Team",
  "MA": "Maintenance",
  "MA-01": "Policy and Procedures",
  "MA-02": "Controlled Maintenance",
  "MA-02(01)": "Record Content",
  "MA-02(02)": "Automated Maintenance Activities",
  "MA-03": "Maintenance Tools",
  "MA-03(01)": "Inspect Tools",
  "MA-03(02)": "Inspect Media",
  "MA-03(03)": "Prevent Unauthorized Removal",
  "MA-03(04)": "Restricted Tool Use",
  "MA-03(05)": "Execution with Privilege",
  "MA-03(06)": "Software Updates and Patches",
  "MA-04": "Nonlocal Maintenance",
  "MA-04(01)": "Logging and Review",
  "MA-04(02)": "Document Nonlocal Maintenance",
  "MA-04(03)": "Comparable Security and Sanitization",
  "MA-04(04)": "Authentication and Separation of Maintenance Sessions",
  "MA-04(05)": "Approvals and Notifications",
  "MA-04(06)": "Cryptographic Protection",
  "MA-04(07)": "Disconnect Verification",
  "MA-05": "Maintenance Personnel",
  "MA-05(01)": "Individuals Without Appropriate Access",
  "MA-05(02)": "Security Clearances for Classified Systems",
  "MA-05(03)": "Citizenship Requirements for Classified Systems",
  "MA-05(04)": "Foreign Nationals",
  "MA-05(05)": "Non-System Maintenance",
  "MA-06": "Timely Maintenance",
  "MA-06(01)": "Preventive Maintenance",
  "MA-06(02)": "Predictive Maintenance",
  "MA-06(03)": "Automated Support for Predictive Maintenance",
  "MA-07": "Field Maintenance",
  "MP": "Media Protection",
  "MP-01": "Policy and Procedures",
  "MP-02": "Media Access",
  "MP-02(01)": "Automated Restricted Access",
  "MP-02(02)": "Cryptographic Protection",
  "MP-03": "Media Marking",
  "MP-04": "Media Storage",
  "MP-04(01)": "Cryptographic Protection",
  "MP-04(02)": "Automated Restricted Access",
  "MP-05": "Media Transport",
  "MP-05(01)": "Protection Outside of Controlled Areas",
  "MP-05(02)": "Documentation of Activities",
  "MP-05(03)": "Custodians",
  "MP-05(04)": "Cryptographic Protection",
  "MP-06": "Media Sanitization",
  "MP-06(01)": "Review, Approve, Track, Document, and Verify",
  "MP-06(02)": "Equipment Testing",
  "MP-06(03)": "Nondestructive Techniques",
  "MP-06(04)": "Controlled Unclassified Information",
  "MP-06(05)": "Classified Information",
  "MP-06(06)": "Media Destruction",
  "MP-06(07)": "Dual Authorization",
  "MP-06(08)": "Remote Purging or Wiping of Information",
  "MP-07": "Media Use",
  "MP-07(01)": "Prohibit Use Without Owner",
  "MP-07(02)": "Prohibit Use of Sanitization-Resistant Media",
  "MP-08": "Media Downgrading",
  "MP-08(01)": "Documentation of Process",
  "MP-08(02)": "Equipment Testing",
  "MP-08(03)": "Controlled Unclassified Information",
  "MP-08(04)": "Classified Information",
  "PE": "Physical and Environmental Protection",
  "PE-01": "Policy and Procedures",
  "PE-02": "Physical Access Authorizations",
  "PE-02(01)": "Access by Position or Role",
  "PE-02(02)": "Two Forms of Identification",
  "PE-02(03)": "Restrict Unescorted Access",
  "PE-03": "Physical Access Control",
  "PE-03(01)": "System Access",
  "PE-03(02)": "Facility and Systems",
  "PE-03(03)": "Continuous Guards",
  "PE-03(04)": "Lockable Casings",
  "PE-03(05)": "Tamper Protection",
  "PE-03(06)": "Facility Penetration Testing",
  "PE-03(07)": "Physical Barriers",
  "PE-03(08)": "Access Control Vestibules",
  "PE-04": "Access Control for Transmission",
  "PE-05": "Access Control for Output Devices",
  "PE-05(01)": "Access to Output by Authorized Individuals",
  "PE-05(02)": "Link to Individual Identity",
  "PE-05(03)": "Marking Output Devices",
  "PE-06": "Monitoring Physical Access",
  "PE-06(01)": "Intrusion Alarms and Surveillance Equipment",
  "PE-06(02)": "Automated Intrusion Recognition and Responses",
  "PE-06(03)": "Video Surveillance",
  "PE-06(04)": "Monitoring Physical Access to Systems",
  "PE-07": "Visitor Control",
  "PE-08": "Visitor Access Records",
  "PE-08(01)": "Automated Records Maintenance and Review",
  "PE-08(02)": "Physical Access Records",
  "PE-08(03)": "Limit Personally Identifiable Information Elements",
  "PE-09": "Power Equipment and Cabling",
  "PE-09(01)": "Redundant Cabling",
  "PE-09(02)": "Automatic Voltage Controls",
  "PE-10": "Emergency Shutoff",
  "PE-10(01)": "Accidental and Unauthorized Activation",
  "PE-11": "Emergency Power",
  "PE-11(01)": "Alternate Power Supply — Minimal Operational Capability",
  "PE-11(02)": "Alternate Power Supply — Self-Contained",
  "PE-12": "Emergency Lighting",
  "PE-12(01)": "Essential Mission and Business Functions",
  "PE-13": "Fire Protection",
  "PE-13(01)": "Detection Systems — Automatic Activation and Notification",
  "PE-13(02)": "Suppression Systems — Automatic Activation and Notification",
  "PE-13(03)": "Automatic Fire Suppression",
  "PE-13(04)": "Inspections",
  "PE-14": "Environmental Controls",
  "PE-14(01)": "Automatic Controls",
  "PE-14(02)": "Monitoring with Alarms and Notifications",
  "PE-15": "Water Damage Protection",
  "PE-15(01)": "Automation Support",
  "PE-16": "Delivery and Removal",
  "PE-17": "Alternate Work Site",
  "PE-18": "Location of System Components",
  "PE-18(01)": "Facility Site",
  "PE-19": "Information Leakage",
  "PE-19(01)": "National Emissions Policies and Procedures",
  "PE-20": "Asset Monitoring and Tracking",
  "PE-21": "Electromagnetic Pulse Protection",
  "PE-22": "Component Marking",
  "PE-23": "Facility Location",
  "PL": "Planning",
  "PL-01": "Policy and Procedures",
  "PL-02": "System Security and Privacy Plans",
  "PL-02(01)": "Concept of Operations",
  "PL-02(02)": "Functional Architecture",
  "PL-02(03)": "Plan and Coordinate with Other Organizational Entities",
  "PL-03": "System Security Plan Update",
  "PL-04": "Rules of Behavior",
  "PL-04(01)": "Social Media and External Site/Application Usage Restrictions",
  "PL-05": "Privacy Impact Assessment",
  "PL-06": "Security-Related Activity Planning",
  "PL-07": "Concept of Operations",
  "PL-08": "Security and Privacy Architectures",
  "PL-08(01)": "Defense in Depth",
  "PL-08(02)": "Supplier Diversity",
  "PL-09": "Central Management",
  "PL-10": "Baseline Selection",
  "PL-11": "Baseline Tailoring",
  "PM": "Program Management",
  "PM-01": "Information Security Program Plan",
  "PM-02": "Information Security Program Leadership Role",
  "PM-03": "Information Security and Privacy Resources",
  "PM-04": "Plan of Action and Milestones Process",
  "PM-05": "System Inventory",
  "PM-05(01)": "Inventory of Personally Identifiable Information",
  "PM-06": "Measures of Performance",
  "PM-07": "Enterprise Architecture",
  "PM-07(01)": "Offloading",
  "PM-08": "Critical Infrastructure Plan",
  "PM-09": "Risk Management Strategy",
  "PM-10": "Authorization Process",
  "PM-11": "Mission and Business Process Definition",
  "PM-12": "Insider Threat Program",
  "PM-13": "Security and Privacy Workforce",
  "PM-14": "Testing, Training, and Monitoring",
  "PM-15": "Security and Privacy Groups and Associations",
  "PM-16": "Threat Awareness Program",
  "PM-16(01)": "Automated Means for Sharing Threat Intelligence",
  "PM-17": "Protecting Controlled Unclassified Information on External Systems",
  "PM-18": "Privacy Program Plan",
  "PM-19": "Privacy Program Leadership Role",
  "PM-20": "Dissemination of Privacy Program Information",
  "PM-20(01)": "Privacy Policies on Websites, Applications, and Digital Services",
  "PM-21": "Accounting of Disclosures",
  "PM-22": "Personally Identifiable Information Quality Management",
  "PM-23": "Data Governance Body",
  "PM-24": "Data Integrity Board",
  "PM-25": "Minimization of Personally Identifiable Information Used in Testing, Training, and Research",
  "PM-26": "Complaint Management",
  "PM-27": "Privacy Reporting",
  "PM-28": "Risk Framing",
  "PM-29": "Risk Management Program Leadership Roles",
  "PM-30": "Supply Chain Risk Management Strategy",
  "PM-30(01)": "Suppliers of Critical or Mission-Essential Items",
  "PM-31": "Continuous Monitoring Strategy",
  "PM-32": "Purposing",
  "PS": "Personnel Security",
  "PS-01": "Policy and Procedures",
  "PS-02": "Position Risk Designation",
  "PS-03": "Personnel Screening",
  "PS-03(01)": "Classified Information",
  "PS-03(02)": "Formal Indoctrination",
  "PS-03(03)": "Information Requiring Special Protective Measures",
  "PS-03(04)": "Citizenship Requirements",
  "PS-04": "Personnel Termination",
  "PS-04(01)": "Post-Employment Requirements",
  "PS-04(02)": "Automated Actions",
  "PS-05": "Personnel Transfer",
  "PS-06": "Access Agreements",
  "PS-06(01)": "Information Requiring Special Protection",
  "PS-06(02)": "Classified Information Requiring Special Protection",
  "PS-06(03)": "Post-Employment Requirements",
  "PS-07": "External Personnel Security",
  "PS-08": "Personnel Sanctions",
  "PS-09": "Position Descriptions",
  "PT": "Personally Identifiable Information Processing and Transparency",
  "PT-01": "Policy and Procedures",
  "PT-02": "Authority to Process Personally Identifiable Information",
  "PT-02(01)": "Data Tagging",
  "PT-02(02)": "Automation",
  "PT-03": "Personally Identifiable Information Processing Purposes",
  "PT-03(01)": "Data Tagging",
  "PT-03(02)": "Automation",
  "PT-04": "Consent",
  "PT-04(01)": "Tailored Consent",
  "PT-04(02)": "Just-In-Time Consent",
  "PT-04(03)": "Revocation",
  "PT-05": "Privacy Notice",
  "PT-05(01)": "Just-In-Time Notice",
  "PT-05(02)": "Privacy Act Statements",
  "PT-06": "System of Records Notice",
  "PT-06(01)": "Routine Uses",
  "PT-06(02)": "Exemption Rules",
  "PT-07": "Specific Categories of Personally Identifiable Information",
  "PT-07(01)": "Social Security Numbers",
  "PT-07(02)": "First Amendment Information",
  "PT-08": "Computer Matching Requirements",
  "RA": "Risk Assessment",
  "RA-01": "Policy and Procedures",
  "RA-02": "Security Categorization",
  "RA-02(01)": "Impact-Level Prioritization",
  "RA-03": "Risk Assessment",
  "RA-03(01)": "Supply Chain Risk Assessment",
  "RA-03(02)": "Use of All-Source Intelligence",
  "RA-03(03)": "Dynamic Threat Awareness",
  "RA-03(04)": "Predictive Cyber Analytics",
  "RA-04": "Risk Assessment Update",
  "RA-05": "Vulnerability Monitoring and Scanning",
  "RA-05(01)": "Update Tool Capability",
  "RA-05(02)": "Update Vulnerabilities to Be Scanned",
  "RA-05(03)": "Breadth and Depth of Coverage",
  "RA-05(04)": "Discoverable Information",
  "RA-05(05)": "Privileged Access",
  "RA-05(06)": "Automated Trend Analyses",
  "RA-05(07)": "Automated Detection and Notification of Unauthorized Components",
  "RA-05(08)": "Review Historic Audit Logs",
  "RA-05(09)": "Penetration Testing and Analyses",
  "RA-05(10)": "Correlate Scanning Information",
  "RA-05(11)": "Public Disclosure Program",
  "RA-06": "Technical Surveillance Countermeasures Survey",
  "RA-07": "Risk Response",
  "RA-08": "Privacy Impact Assessments",
  "RA-09": "Criticality Analysis",
  "RA-10": "Threat Hunting",
  "SA": "System and Services Acquisition",
  "SA-01": "Policy and Procedures",
  "SA-02": "Allocation of Resources",
  "SA-03": "System Development Life Cycle",
  "SA-03(01)": "Manage Preproduction Environment",
  "SA-03(02)": "Use of Live or Operational Data",
  "SA-03(03)": "Technology Refresh",
  "SA-04": "Acquisition Process",
  "SA-04(01)": "Functional Properties of Controls",
  "SA-04(02)": "Design and Implementation Information for Controls",
  "SA-04(03)": "Development Methods, Techniques, and Practices",
  "SA-04(04)": "Assignment of Components to Systems",
  "SA-04(05)": "System, Component, and Service Configurations",
  "SA-04(06)": "Use of Information Assurance Products",
  "SA-04(07)": "NIAP-Approved Protection Profiles",
  "SA-04(08)": "Continuous Monitoring Plan for Controls",
  "SA-04(09)": "Functions, Ports, Protocols, and Services in Use",
  "SA-04(10)": "Use of Approved PIV Products",
  "SA-04(11)": "System of Records",
  "SA-04(12)": "Data Ownership",
  "SA-05": "System Documentation",
  "SA-05(01)": "Functional Properties of Security Controls",
  "SA-05(02)": "Security-Relevant External System Interfaces",
  "SA-05(03)": "High-Level Design",
  "SA-05(04)": "Low-Level Design",
  "SA-05(05)": "Source Code",
  "SA-06": "Software Usage Restrictions",
  "SA-07": "User-Installed Software",
  "SA-08": "Security and Privacy Engineering Principles",
  "SA-08(01)": "Clear Abstractions",
  "SA-08(02)": "Least Common Mechanism",
  "SA-08(03)": "Modularity and Layering",
  "SA-08(04)": "Partially Ordered Dependencies",
  "SA-08(05)": "Efficiently Mediated Access",
  "SA-08(06)": "Minimized Sharing",
  "SA-08(07)": "Reduced Complexity",
  "SA-08(08)": "Secure Evolvability",
  "SA-08(09)": "Trusted Components",
  "SA-08(10)": "Hierarchical Trust",
  "SA-08(11)": "Inverse Modification Threshold",
  "SA-08(12)": "Hierarchical Protection",
  "SA-08(13)": "Minimized Security Elements",
  "SA-08(14)": "Least Privilege",
  "SA-08(15)": "Predicate Permission",
  "SA-08(16)": "Self-Reliant Trustworthiness",
  "SA-08(17)": "Secure Distributed Composition",
  "SA-08(18)": "Trusted Communications Channels",
  "SA-08(19)": "Continuous Protection",
  "SA-08(20)": "Secure Metadata Management",
  "SA-08(21)": "Self-Analysis",
  "SA-08(22)": "Accountability and Traceability",
  "SA-08(23)": "Secure Defaults",
  "SA-08(24)": "Secure Failure and Recovery",
  "SA-08(25)": "Economic Security",
  "SA-08(26)": "Performance Security",
  "SA-08(27)": "Human Factored Security",
  "SA-08(28)": "Acceptable Security",
  "SA-08(29)": "Repeatable and Documented Procedures",
  "SA-08(30)": "Procedural Rigor",
  "SA-08(31)": "Secure System Modification",
  "SA-08(32)": "Sufficient Documentation",
  "SA-08(33)": "Minimization",
  "SA-09": "External System Services",
  "SA-09(01)": "Risk Assessments and Organizational Approvals",
  "SA-09(02)": "Identification of Functions, Ports, Protocols, and Services",
  "SA-09(03)": "Establish and Maintain Trust Relationship with Providers",
  "SA-09(04)": "Consistent Interests of Consumers and Providers",
  "SA-09(05)": "Processing, Storage, and Service Location",
  "SA-09(06)": "Organization-Controlled Cryptographic Keys",
  "SA-09(07)": "Organization-Controlled Integrity Checking",
  "SA-09(08)": "Processing and Storage Location — U.s. Jurisdiction",
  "SA-10": "Developer Configuration Management",
  "SA-10(01)": "Software and Firmware Integrity Verification",
  "SA-10(02)": "Alternative Configuration Management Processes",
  "SA-10(03)": "Hardware Integrity Verification",
  "SA-10(04)": "Trusted Generation",
  "SA-10(05)": "Mapping Integrity for Version Control",
  "SA-10(06)": "Trusted Distribution",
  "SA-10(07)": "Security and Privacy Representatives",
  "SA-11": "Developer Testing and Evaluation",
  "SA-11(01)": "Static Code Analysis",
  "SA-11(02)": "Threat Modeling and Vulnerability Analyses",
  "SA-11(03)": "Independent Verification of Assessment Plans and Evidence",
  "SA-11(04)": "Manual Code Reviews",
  "SA-11(05)": "Penetration Testing",
  "SA-11(06)": "Attack Surface Reviews",
  "SA-11(07)": "Verify Scope of Testing and Evaluation",
  "SA-11(08)": "Dynamic Code Analysis",
  "SA-11(09)": "Interactive Application Security Testing",
  "SA-12": "Supply Chain Protection",
  "SA-12(01)": "Acquisition Strategies / Tools / Methods",
  "SA-12(02)": "Supplier Reviews",
  "SA-12(03)": "Trusted Shipping and Warehousing",
  "SA-12(04)": "Diversity of Suppliers",
  "SA-12(05)": "Limitation of Harm",
  "SA-12(06)": "Minimizing Procurement Time",
  "SA-12(07)": "Assessments Prior to Selection / Acceptance / Update",
  "SA-12(08)": "Use of All-Source Intelligence",
  "SA-12(09)": "Operations Security",
  "SA-12(10)": "Validate as Genuine and Not Altered",
  "SA-12(11)": "Penetration Testing / Analysis of Elements, Processes, and Actors",
  "SA-12(12)": "Inter-Organizational Agreements",
  "SA-12(13)": "Critical Information System Components",
  "SA-12(14)": "Identity and Traceability",
  "SA-12(15)": "Processes to Address Weaknesses or Deficiencies",
  "SA-13": "Trustworthiness",
  "SA-14": "Criticality Analysis",
  "SA-14(01)": "Critical Components with No Viable Alternative Sourcing",
  "SA-15": "Development Process, Standards, and Tools",
  "SA-15(01)": "Quality Metrics",
  "SA-15(02)": "Security and Privacy Tracking Tools",
  "SA-15(03)": "Criticality Analysis",
  "SA-15(04)": "Threat Modeling and Vulnerability Analysis",
  "SA-15(05)": "Attack Surface Reduction",
  "SA-15(06)": "Continuous Improvement",
  "SA-15(07)": "Automated Vulnerability Analysis",
  "SA-15(08)": "Reuse of Threat and Vulnerability Information",
  "SA-15(09)": "Use of Live Data",
  "SA-15(10)": "Incident Response Plan",
  "SA-15(11)": "Archive System or Component",
  "SA-15(12)": "Minimize Personally Identifiable Information",
  "SA-15(13)": "Logging Syntax",
  "SA-16": "Developer-Provided Training",
  "SA-17": "Developer Security and Privacy Architecture and Design",
  "SA-17(01)": "Formal Policy Model",
  "SA-17(02)": "Security-Relevant Components",
  "SA-17(03)": "Formal Correspondence",
  "SA-17(04)": "Informal Correspondence",
  "SA-17(05)": "Conceptually Simple Design",
  "SA-17(06)": "Structure for Testing",
  "SA-17(07)": "Structure for Least Privilege",
  "SA-17(08)": "Orchestration",
  "SA-17(09)": "Design Diversity",
  "SA-18": "Tamper Resistance and Detection",
  "SA-18(01)": "Multiple Phases of System Development Life Cycle",
  "SA-18(02)": "Inspection of Systems or Components",
  "SA-19": "Component Authenticity",
  "SA-19(01)": "Anti-Counterfeit Training",
  "SA-19(02)": "Configuration Control for Component Service and Repair",
  "SA-19(03)": "Component Disposal",
  "SA-19(04)": "Anti-Counterfeit Scanning",
  "SA-20": "Customized Development of Critical Components",
  "SA-21": "Developer Screening",
  "SA-21(01)": "Validation of Screening",
  "SA-22": "Unsupported System Components",
  "SA-22(01)": "Alternative Sources for Continued Support",
  "SA-23": "Specialization",
  "SA-24": "Design for Cyber Resiliency",
  "SC": "System and Communications Protection",
  "SC-01": "Policy and Procedures",
  "SC-02": "Separation of System and User Functionality",
  "SC-02(01)": "Interfaces for Non-Privileged Users",
  "SC-02(02)": "Disassociability",
  "SC-03": "Security Function Isolation",
  "SC-03(01)": "Hardware Separation",
  "SC-03(02)": "Access and Flow Control Functions",
  "SC-03(03)": "Minimize Nonsecurity Functionality",
  "SC-03(04)": "Module Coupling and Cohesiveness",
  "SC-03(05)": "Layered Structures",
  "SC-04": "Information in Shared System Resources",
  "SC-04(01)": "Security Levels",
  "SC-04(02)": "Multilevel or Periods Processing",
  "SC-05": "Denial-Of-Service Protection",
  "SC-05(01)": "Restrict Ability to Attack Other Systems",
  "SC-05(02)": "Capacity, Bandwidth, and Redundancy",
  "SC-05(03)": "Detection and Monitoring",
  "SC-06": "Resource Availability",
  "SC-07": "Boundary Protection",
  "SC-07(01)": "Physically Separated Subnetworks",
  "SC-07(02)": "Public Access",
  "SC-07(03)": "Access Points",
  "SC-07(04)": "External Telecommunications Services",
  "SC-07(05)": "Deny by Default — Allow by Exception",
  "SC-07(06)": "Response to Recognized Failures",
  "SC-07(07)": "Split Tunneling for Remote Devices",
  "SC-07(08)": "Route Traffic to Authenticated Proxy Servers",
  "SC-07(09)": "Restrict Threatening Outgoing Communications Traffic",
  "SC-07(10)": "Prevent Exfiltration",
  "SC-07(11)": "Restrict Incoming Communications Traffic",
  "SC-07(12)": "Host-Based Protection",
  "SC-07(13)": "Isolation of Security Tools, Mechanisms, and Support Components",
  "SC-07(14)": "Protect Against Unauthorized Physical Connections",
  "SC-07(15)": "Networked Privileged Accesses",
  "SC-07(16)": "Prevent Discovery of System Components",
  "SC-07(17)": "Automated Enforcement of Protocol Formats",
  "SC-07(18)": "Fail Secure",
  "SC-07(19)": "Block Communication from Non-Organizationally Configured Hosts",
  "SC-07(20)": "Dynamic Isolation and Segregation",
  "SC-07(21)": "Isolation of System Components",
  "SC-07(22)": "Separate Subnets for Connecting to Different Security Domains",
  "SC-07(23)": "Disable Sender Feedback on Protocol Validation Failure",
  "SC-07(24)": "Personally Identifiable Information",
  "SC-07(25)": "Unclassified National Security System Connections",
  "SC-07(26)": "Classified National Security System Connections",
  "SC-07(27)": "Unclassified Non-National Security System Connections",
  "SC-07(28)": "Connections to Public Networks",
  "SC-07(29)": "Separate Subnets to Isolate Functions",
  "SC-08": "Transmission Confidentiality and Integrity",
  "SC-08(01)": "Cryptographic Protection",
  "SC-08(02)": "Pre- and Post-Transmission Handling",
  "SC-08(03)": "Cryptographic Protection for Message Externals",
  "SC-08(04)": "Conceal or Randomize Communications",
  "SC-08(05)": "Protected Distribution System",
  "SC-09": "Transmission Confidentiality",
  "SC-10": "Network Disconnect",
  "SC-11": "Trusted Path",
  "SC-11(01)": "Irrefutable Communications Path",
  "SC-12": "Cryptographic Key Establishment and Management",
  "SC-12(01)": "Availability",
  "SC-12(02)": "Symmetric Keys",
  "SC-12(03)": "Asymmetric Keys",
  "SC-12(04)": "PKI Certificates",
  "SC-12(05)": "PKI Certificates / Hardware Tokens",
  "SC-12(06)": "Physical Control of Keys",
  "SC-13": "Cryptographic Protection",
  "SC-13(01)": "FIPS-Validated Cryptography",
  "SC-13(02)": "NSA-Approved Cryptography",
  "SC-13(03)": "Individuals Without Formal Access Approvals",
  "SC-13(04)": "Digital Signatures",
  "SC-14": "Public Access Protections",
  "SC-15": "Collaborative Computing Devices and Applications",
  "SC-15(01)": "Physical or Logical Disconnect",
  "SC-15(02)": "Blocking Inbound and Outbound Communications Traffic",
  "SC-15(03)": "Disabling and Removal in Secure Work Areas",
  "SC-15(04)": "Explicitly Indicate Current Participants",
  "SC-16": "Transmission of Security and Privacy Attributes",
  "SC-16(01)": "Integrity Verification",
  "SC-16(02)": "Anti-Spoofing Mechanisms",
  "SC-16(03)": "Cryptographic Binding",
  "SC-17": "Public Key Infrastructure Certificates",
  "SC-18": "Mobile Code",
  "SC-18(01)": "Identify Unacceptable Code and Take Corrective Actions",
  "SC-18(02)": "Acquisition, Development, and Use",
  "SC-18(03)": "Prevent Downloading and Execution",
  "SC-18(04)": "Prevent Automatic Execution",
  "SC-18(05)": "Allow Execution Only in Confined Environments",
  "SC-19": "Voice Over Internet Protocol",
  "SC-20": "Secure Name/Address Resolution Service (Authoritative Source)",
  "SC-20(01)": "Child Subspaces",
  "SC-20(02)": "Data Origin and Integrity",
  "SC-21": "Secure Name/Address Resolution Service (Recursive or Caching Resolver)",
  "SC-21(01)": "Data Origin and Integrity",
  "SC-22": "Architecture and Provisioning for Name/Address Resolution Service",
  "SC-23": "Session Authenticity",
  "SC-23(01)": "Invalidate Session Identifiers at Logout",
  "SC-23(02)": "User-Initiated Logouts and Message Displays",
  "SC-23(03)": "Unique System-Generated Session Identifiers",
  "SC-23(04)": "Unique Session Identifiers with Randomization",
  "SC-23(05)": "Allowed Certificate Authorities",
  "SC-24": "Fail in Known State",
  "SC-25": "Thin Nodes",
  "SC-26": "Decoys",
  "SC-26(01)": "Detection of Malicious Code",
  "SC-27": "Platform-Independent Applications",
  "SC-28": "Protection of Information at Rest",
  "SC-28(01)": "Cryptographic Protection",
  "SC-28(02)": "Offline Storage",
  "SC-28(03)": "Cryptographic Keys",
  "SC-29": "Heterogeneity",
  "SC-29(01)": "Virtualization Techniques",
  "SC-30": "Concealment and Misdirection",
  "SC-30(01)": "Virtualization Techniques",
  "SC-30(02)": "Randomness",
  "SC-30(03)": "Change Processing and Storage Locations",
  "SC-30(04)": "Misleading Information",
  "SC-30(05)": "Concealment of System Components",
  "SC-31": "Covert Channel Analysis",
  "SC-31(01)": "Test Covert Channels for Exploitability",
  "SC-31(02)": "Maximum Bandwidth",
  "SC-31(03)": "Measure Bandwidth in Operational Environments",
  "SC-32": "System Partitioning",
  "SC-32(01)": "Separate Physical Domains for Privileged Functions",
  "SC-33": "Transmission Preparation Integrity",
  "SC-34": "Non-Modifiable Executable Programs",
  "SC-34(01)": "No Writable Storage",
  "SC-34(02)": "Integrity Protection on Read-Only Media",
  "SC-34(03)": "Hardware-Based Protection",
  "SC-35": "External Malicious Code Identification",
  "SC-36": "Distributed Processing and Storage",
  "SC-36(01)": "Polling Techniques",
  "SC-36(02)": "Synchronization",
  "SC-37": "Out-Of-Band Channels",
  "SC-37(01)": "Ensure Delivery and Transmission",
  "SC-38": "Operations Security",
  "SC-39": "Process Isolation",
  "SC-39(01)": "Hardware Separation",
  "SC-39(02)": "Separate Execution Domain Per Thread",
  "SC-40": "Wireless Link Protection",
  "SC-40(01)": "Electromagnetic Interference",
  "SC-40(02)": "Reduce Detection Potential",
  "SC-40(03)": "Imitative or Manipulative Communications Deception",
  "SC-40(04)": "Signal Parameter Identification",
  "SC-41": "Port and I/O Device Access",
  "SC-42": "Sensor Capability and Data",
  "SC-42(01)": "Reporting to Authorized Individuals or Roles",
  "SC-42(02)": "Authorized Use",
  "SC-42(03)": "Prohibit Use of Devices",
  "SC-42(04)": "Notice of Collection",
  "SC-42(05)": "Collection Minimization",
  "SC-43": "Usage Restrictions",
  "SC-44": "Detonation Chambers",
  "SC-45": "System Time Synchronization",
  "SC-45(01)": "Synchronization with Authoritative Time Source",
  "SC-45(02)": "Secondary Authoritative Time Source",
  "SC-46": "Cross Domain Policy Enforcement",
  "SC-47": "Alternate Communications Paths",
  "SC-48": "Sensor Relocation",
  "SC-48(01)": "Dynamic Relocation of Sensors or Monitoring Capabilities",
  "SC-49": "Hardware-Enforced Separation and Policy Enforcement",
  "SC-50": "Software-Enforced Separation and Policy Enforcement",
  "SC-51": "Hardware-Based Protection",
  "SI": "System and Information Integrity",
  "SI-01": "Policy and Procedures",
  "SI-02": "Flaw Remediation",
  "SI-02(01)": "Central Management",
  "SI-02(02)": "Automated Flaw Remediation Status",
  "SI-02(03)": "Time to Remediate Flaws and Benchmarks for Corrective Actions",
  "SI-02(04)": "Automated Patch Management Tools",
  "SI-02(05)": "Automatic Software and Firmware Updates",
  "SI-02(06)": "Removal of Previous Versions of Software and Firmware",
  "SI-02(07)": "Root Cause Analysis",
  "SI-03": "Malicious Code Protection",
  "SI-03(01)": "Central Management",
  "SI-03(02)": "Automatic Updates",
  "SI-03(03)": "Non-Privileged Users",
  "SI-03(04)": "Updates Only by Privileged Users",
  "SI-03(05)": "Portable Storage Devices",
  "SI-03(06)": "Testing and Verification",
  "SI-03(07)": "Nonsignature-Based Detection",
  "SI-03(08)": "Detect Unauthorized Commands",
  "SI-03(09)": "Authenticate Remote Commands",
  "SI-03(10)": "Malicious Code Analysis",
  "SI-04": "System Monitoring",
  "SI-04(01)": "System-Wide Intrusion Detection System",
  "SI-04(02)": "Automated Tools and Mechanisms for Real-Time Analysis",
  "SI-04(03)": "Automated Tool and Mechanism Integration",
  "SI-04(04)": "Inbound and Outbound Communications Traffic",
  "SI-04(05)": "System-Generated Alerts",
  "SI-04(06)": "Restrict Non-Privileged Users",
  "SI-04(07)": "Automated Response to Suspicious Events",
  "SI-04(08)": "Protection of Monitoring Information",
  "SI-04(09)": "Testing of Monitoring Tools and Mechanisms",
  "SI-04(10)": "Visibility of Encrypted Communications",
  "SI-04(11)": "Analyze Communications Traffic Anomalies",
  "SI-04(12)": "Automated Organization-Generated Alerts",
  "SI-04(13)": "Analyze Traffic and Event Patterns",
  "SI-04(14)": "Wireless Intrusion Detection",
  "SI-04(15)": "Wireless to Wireline Communications",
  "SI-04(16)": "Correlate Monitoring Information",
  "SI-04(17)": "Integrated Situational Awareness",
  "SI-04(18)": "Analyze Traffic and Covert Exfiltration",
  "SI-04(19)": "Risk for Individuals",
  "SI-04(20)": "Privileged Users",
  "SI-04(21)": "Probationary Periods",
  "SI-04(22)": "Unauthorized Network Services",
  "SI-04(23)": "Host-Based Devices",
  "SI-04(24)": "Indicators of Compromise",
  "SI-04(25)": "Optimize Network Traffic Analysis",
  "SI-05": "Security Alerts, Advisories, and Directives",
  "SI-05(01)": "Automated Alerts and Advisories",
  "SI-06": "Security and Privacy Function Verification",
  "SI-06(01)": "Notification of Failed Security Tests",
  "SI-06(02)": "Automation Support for Distributed Testing",
  "SI-06(03)": "Report Verification Results",
  "SI-07": "Software, Firmware, and Information Integrity",
  "SI-07(01)": "Integrity Checks",
  "SI-07(02)": "Automated Notifications of Integrity Violations",
  "SI-07(03)": "Centrally Managed Integrity Tools",
  "SI-07(04)": "Tamper-Evident Packaging",
  "SI-07(05)": "Automated Response to Integrity Violations",
  "SI-07(06)": "Cryptographic Protection",
  "SI-07(07)": "Integration of Detection and Response",
  "SI-07(08)": "Auditing Capability for Significant Events",
  "SI-07(09)": "Verify Boot Process",
  "SI-07(10)": "Protection of Boot Firmware",
  "SI-07(11)": "Confined Environments with Limited Privileges",
  "SI-07(12)": "Integrity Verification",
  "SI-07(13)": "Code Execution in Protected Environments",
  "SI-07(14)": "Binary or Machine Executable Code",
  "SI-07(15)": "Code Authentication",
  "SI-07(16)": "Time Limit on Process Execution Without Supervision",
  "SI-07(17)": "Runtime Application Self-Protection",
  "SI-08": "Spam Protection",
  "SI-08(01)": "Central Management",
  "SI-08(02)": "Automatic Updates",
  "SI-08(03)": "Continuous Learning Capability",
  "SI-09": "Information Input Restrictions",
  "SI-10": "Information Input Validation",
  "SI-10(01)": "Manual Override Capability",
  "SI-10(02)": "Review and Resolve Errors",
  "SI-10(03)": "Predictable Behavior",
  "SI-10(04)": "Timing Interactions",
  "SI-10(05)": "Restrict Inputs to Trusted Sources and Approved Formats",
  "SI-10(06)": "Injection Prevention",
  "SI-11": "Error Handling",
  "SI-12": "Information Management and Retention",
  "SI-12(01)": "Limit Personally Identifiable Information Elements",
  "SI-12(02)": "Minimize Personally Identifiable Information in Testing, Training, and Research",
  "SI-12(03)": "Information Disposal",
  "SI-13": "Predictable Failure Prevention",
  "SI-13(01)": "Transferring Component Responsibilities",
  "SI-13(02)": "Time Limit on Process Execution Without Supervision",
  "SI-13(03)": "Manual Transfer Between Components",
  "SI-13(04)": "Standby Component Installation and Notification",
  "SI-13(05)": "Failover Capability",
  "SI-14": "Non-Persistence",
  "SI-14(01)": "Refresh from Trusted Sources",
  "SI-14(02)": "Non-Persistent Information",
  "SI-14(03)": "Non-Persistent Connectivity",
  "SI-15": "Information Output Filtering",
  "SI-16": "Memory Protection",
  "SI-17": "Fail-Safe Procedures",
  "SI-18": "Personally Identifiable Information Quality Operations",
  "SI-18(01)": "Automation Support",
  "SI-18(02)": "Data Tags",
  "SI-18(03)": "Collection",
  "SI-18(04)": "Individual Requests",
  "SI-18(05)": "Notice of Correction or Deletion",
  "SI-19": "De-Identification",
  "SI-19(01)": "Collection",
  "SI-19(02)": "Archiving",
  "SI-19(03)": "Release",
  "SI-19(04)": "Removal, Masking, Encryption, Hashing, or Replacement of Direct Identifiers",
  "SI-19(05)": "Statistical Disclosure Control",
  "SI-19(06)": "Differential Privacy",
  "SI-19(07)": "Validated Algorithms and Software",
  "SI-19(08)": "Motivated Intruder",
  "SI-20": "Tainting",
  "SI-21": "Information Refresh",
  "SI-22": "Information Diversity",
  "SI-23": "Information Fragmentation",
  "SR": "Supply Chain Risk Management",
  "SR-01": "Policy and Procedures",
  "SR-02": "Supply Chain Risk Management Plan",
  "SR-02(01)": "Establish SCRM Team",
  "SR-03": "Supply Chain Controls and Processes",
  "SR-03(01)": "Diverse Supply Base",
  "SR-03(02)": "Limitation of Harm",
  "SR-03(03)": "Sub-Tier Flow Down",
  "SR-04": "Provenance",
  "SR-04(01)": "Identity",
  "SR-04(02)": "Track and Trace",
  "SR-04(03)": "Validate as Genuine and Not Altered",
  "SR-04(04)": "Supply Chain Integrity — Pedigree",
  "SR-05": "Acquisition Strategies, Tools, and Methods",
  "SR-05(01)": "Adequate Supply",
  "SR-05(02)": "Assessments Prior to Selection, Acceptance, Modification, or Update",
  "SR-06": "Supplier Assessments and Reviews",
  "SR-06(01)": "Testing and Analysis",
  "SR-07": "Supply Chain Operations Security",
  "SR-08": "Notification Agreements",
  "SR-09": "Tamper Resistance and Detection",
  "SR-09(01)": "Multiple Stages of System Development Life Cycle",
  "SR-10": "Inspection of Systems or Components",
  "SR-11": "Component Authenticity",
  "SR-11(01)": "Anti-Counterfeit Training",
  "SR-11(02)": "Configuration Control for Component Service and Repair",
  "SR-11(03)": "Anti-Counterfeit Scanning",
  "SR-12": "Component Disposal",
};

/** NIST SP 800-171 Rev. 3 -- families and security requirements. */
const NIST_800_171: Record<string, string> = {
  "03.01": "Access Control",
  "03.01.01.a": "Define the types of system accounts allowed and prohibited.",
  "03.01.01.b": "Create, enable, modify, disable, and remove system accounts in accordance with policy, procedures, prerequisites, and criteria.",
  "03.01.01.c": "Specify:",
  "03.01.01.c.01": "Authorized users of the system,",
  "03.01.01.c.02": "Group and role membership, and",
  "03.01.01.c.03": "Access authorizations (i.e., privileges) for each account.",
  "03.01.01.d": "Authorize access to the system based on:",
  "03.01.01.d.01": "A valid access authorization and",
  "03.01.01.d.02": "Intended system usage.",
  "03.01.01.e": "Monitor the use of system accounts.",
  "03.01.01.f": "Disable system accounts when:",
  "03.01.01.f.01": "The accounts have expired,",
  "03.01.01.f.02": "The accounts have been inactive for [Assignment: organization-defined time period],",
  "03.01.01.f.03": "The accounts are no longer associated with a user or individual,",
  "03.01.01.f.04": "The accounts are in violation of organizational policy, or",
  "03.01.01.f.05": "Significant risks associated with individuals are discovered.",
  "03.01.01.g": "Notify account managers and designated personnel or roles within:",
  "03.01.01.g.01": "[Assignment: organization-defined time period] when accounts are no longer required.",
  "03.01.01.g.02": "[Assignment: organization-defined time period] when users are terminated or transferred.",
  "03.01.01.g.03": "[Assignment: organization-defined time period] when system usage or the need-to-know changes for an individual.",
  "03.01.01.h": "Require that users log out of the system after [Assignment: organization-defined time period] of expected inactivity or when [Assignment: organization-defined circumstances].",
  "03.01.02": "Enforce approved authorizations for logical access to CUI and system resources in accordance with applicable access control policies.",
  "03.01.03": "Enforce approved authorizations for controlling the flow of CUI within the system and between connected systems.",
  "03.01.04.a": "Identify the duties of individuals requiring separation.",
  "03.01.04.b": "Define system access authorizations to support separation of duties.",
  "03.01.05.a": "Allow only authorized system access for users (or processes acting on behalf of users) that is necessary to accomplish assigned organizational tasks.",
  "03.01.05.b": "Authorize access to [Assignment: organization-defined security functions] and [Assignment: organization-defined security-relevant information].",
  "03.01.05.c": "Review the privileges assigned to roles or classes of users [Assignment: organization-defined frequency] to validate the need for such privileges.",
  "03.01.05.d": "Reassign or remove privileges, as necessary.",
  "03.01.06.a": "Restrict privileged accounts on the system to [Assignment: organization-defined personnel or roles]..",
  "03.01.06.b": "Require that users (or roles) with privileged accounts use non-privileged accounts when accessing non-security functions or non-security information.",
  "03.01.07.a": "Prevent non-privileged users from executing privileged functions.",
  "03.01.07.b": "Log the execution of privileged functions.",
  "03.01.08.a": "Enforce a limit of [Assignment: organization-defined number] consecutive invalid logon attempts by a user during a [Assignment: organization-defined time period].",
  "03.01.08.b": "Automatically [Selection (one or more): lock the account or node for an [Assignment: organization-defined time period]; lock the account or node until released by an administrator; delay next logon prompt; notify system administrator; take other action] when the maximum number of unsuccessful attempts is exceeded.",
  "03.01.09": "Display a system use notification message with privacy and security notices consistent with applicable CUI rules before granting access to the system.",
  "03.01.10.a": "Prevent access to the system by [Selection (one or more): initiating a device lock after [Assignment: organization-defined time period] of inactivity; requiring the user to initiate a device lock before leaving the system unattended].",
  "03.01.10.b": "Retain the device lock until the user reestablishes access using established identification and authentication procedures.",
  "03.01.10.c": "Conceal, via the device lock, information previously visible on the display with a publicly viewable image.",
  "03.01.11": "Terminate a user session automatically after [Assignment: organization-defined conditions or trigger events requiring session disconnect].",
  "03.01.12.a": "Establish usage restrictions, configuration requirements, and connection requirements for each type of allowable remote system access.",
  "03.01.12.b": "Authorize each type of remote system access prior to establishing such connections.",
  "03.01.12.c": "Route remote access to the system through authorized and managed access control points.",
  "03.01.12.d": "Authorize the remote execution of privileged commands and remote access to security-relevant information.",
  "03.01.16.a": "Establish usage restrictions, configuration requirements, and connection requirements for each type of wireless access to the system.",
  "03.01.16.b": "Authorize each type of wireless access to the system prior to establishing such connections.",
  "03.01.16.c": "Disable, when not intended for use, wireless networking capabilities prior to issuance and deployment.",
  "03.01.16.d": "Protect wireless access to the system using authentication and encryption.",
  "03.01.18.a": "Establish usage restrictions, configuration requirements, and connection requirements for mobile devices.",
  "03.01.18.b": "Authorize the connection of mobile devices to the system.",
  "03.01.18.c": "Implement full-device or container-based encryption to protect the confidentiality of CUI on mobile devices.",
  "03.01.20.a": "Prohibit the use of external systems unless the systems are specifically authorized.",
  "03.01.20.b": "Establish the following security requirements to be satisfied on external systems prior to allowing use of or access to those systems by authorized individuals: [Assignment: organization-defined security requirements].",
  "03.01.20.c": "Permit authorized individuals to use external systems to access the organizational system or to process, store, or transmit CUI only after:",
  "03.01.20.c.01": "Verifying that the security requirements on the external systems as specified in the organization’s system security plans have been satisfied and",
  "03.01.20.c.02": "Retaining approved system connection or processing agreements with the organizational entities hosting the external systems.",
  "03.01.20.d": "Restrict the use of organization-controlled portable storage devices by authorized individuals on external systems.",
  "03.01.22.a": "Train authorized individuals to ensure that publicly accessible information does not contain CUI.",
  "03.01.22.b": "Review the content on publicly accessible systems for CUI and remove such information, if discovered.",
  "03.02": "Awareness and Training",
  "03.02.01.a": "Provide security literacy training to system users:",
  "03.02.01.a.01": "As part of initial training for new users and [Assignment: organization-defined frequency] thereafter,",
  "03.02.01.a.02": "When required by system changes or following [Assignment: organization-defined events], and",
  "03.02.01.a.03": "On recognizing and reporting indicators of insider threat, social engineering, and social mining.",
  "03.02.01.b": "Update security literacy training content [Assignment: organization-defined frequency] and following [Assignment: organization-defined events].",
  "03.02.02.a": "Provide role-based security training to organizational personnel:",
  "03.02.02.a.01": "Before authorizing access to the system or CUI, before performing assigned duties, and [Assignment: organization-defined frequency] thereafter",
  "03.02.02.a.02": "When required by system changes or following [Assignment: organization-defined events].",
  "03.02.02.b": "Update role-based training content [Assignment: organization-defined frequency] and following [Assignment: organization-defined events].",
  "03.03": "Audit and Accountability",
  "03.03.01.a": "Specify the following event types selected for logging within the system: [Assignment: organization-defined event types].",
  "03.03.01.b": "Review and update the event types selected for logging [Assignment: organization-defined frequency].",
  "03.03.02.a": "Include the following content in audit records:",
  "03.03.02.a.01": "What type of event occurred",
  "03.03.02.a.02": "When the event occurred",
  "03.03.02.a.03": "Where the event occurred",
  "03.03.02.a.04": "Source of the event",
  "03.03.02.a.05": "Outcome of the event",
  "03.03.02.a.06": "Identity of the individuals, subjects, objects, or entities associated with the event",
  "03.03.02.b": "Provide additional information for audit records as needed.",
  "03.03.03.a": "Generate audit records for the selected event types and audit record content specified in 03.03.01 and 03.03.02.",
  "03.03.03.b": "Retain audit records for a time period consistent with the records retention policy.",
  "03.03.04.a": "Alert organizational personnel or roles within [Assignment: organization-defined time period] in the event of an audit logging process failure.",
  "03.03.04.b": "Take the following additional actions: [Assignment: organization-defined additional actions].",
  "03.03.05.a": "Review and analyze system audit records [Assignment: organization-defined frequency] for indications and the potential impact of inappropriate or unusual activity.",
  "03.03.05.b": "Report findings to organizational personnel or roles.",
  "03.03.05.c": "Analyze and correlate audit records across different repositories to gain organization-wide situational awareness.",
  "03.03.06.a": "Implement an audit record reduction and report generation capability that supports audit record review, analysis, reporting requirements, and after-the-fact investigations of incidents.",
  "03.03.06.b": "Preserve the original content and time ordering of audit records.",
  "03.03.07.a": "Use internal system clocks to generate time stamps for audit records.",
  "03.03.07.b": "Record time stamps for audit records that meet [Assignment: organization-defined granularity of time measurement] and that use Coordinated Universal Time (UTC), have a fixed local time offset from UTC, or include the local time offset as part of the time stamp.",
  "03.03.08.a": "Protect audit information and audit logging tools from unauthorized access, modification, and deletion.",
  "03.03.08.b": "Authorize access to management of audit logging functionality to only a subset of privileged users or roles.",
  "03.04": "Configuration Management",
  "03.04.01.a": "Develop and maintain under configuration control, a current baseline configuration of the system.",
  "03.04.01.b": "Review and update the baseline configuration of the system [Assignment: organization-defined frequency] and when system components are installed or modified.",
  "03.04.02.a": "Establish, document, and implement the following configuration settings for the system that reflect the most restrictive mode consistent with operational requirements: [Assignment: organization-defined configuration settings].",
  "03.04.02.b": "Identify, document, and approve any deviations from established configuration settings.",
  "03.04.03.a": "Define the types of changes to the system that are configuration-controlled.",
  "03.04.03.b": "Review proposed configuration-controlled changes to the system, and approve or disapprove such changes with explicit consideration for security impacts.",
  "03.04.03.c": "Implement and document approved configuration-controlled changes to the system.",
  "03.04.03.d": "Monitor and review activities associated with configuration-controlled changes to the system.",
  "03.04.04.a": "Analyze changes to the system to determine potential security impacts prior to change implementation.",
  "03.04.04.b": "Verify that the security requirements for the system continue to be satisfied after the system changes have been implemented.",
  "03.04.05": "Define, document, approve, and enforce physical and logical access restrictions associated with changes to the system.",
  "03.04.06.a": "Configure the system to provide only mission-essential capabilities.",
  "03.04.06.b": "Prohibit or restrict use of the following functions, ports, protocols, connections, and services: [Assignment: organization-defined functions, ports, protocols, connections, and services].",
  "03.04.06.c": "Review the system [Assignment: organization-defined frequency] to identify unnecessary or nonsecure functions, ports, protocols, connections, and services.",
  "03.04.06.d": "Disable or remove functions, ports, protocols, connections, and services that are unnecessary or nonsecure.",
  "03.04.08.a": "Identify software programs authorized to execute on the system.",
  "03.04.08.b": "Implement a deny-all, allow-by-exception policy for the execution of authorized software programs on the system.",
  "03.04.08.c": "Review and update the list of authorized software programs [Assignment: organization-defined frequency].",
  "03.04.10.a": "Develop and document an inventory of system components.",
  "03.04.10.b": "Review and update the system component inventory [Assignment: organization-defined frequency].",
  "03.04.10.c": "Update the system component inventory as part of installations, removals, and system updates.",
  "03.04.11.a": "Identify and document the location of CUI and the system components on which the information is processed and stored.",
  "03.04.11.b": "Document changes to the system or system component location where CUI is processed and stored.",
  "03.04.12.a": "Issue systems or system components with the following configurations to individuals traveling to high-risk locations: [Assignment: organization-defined system configurations].",
  "03.04.12.b": "Apply the following security requirements to the systems or components when the individuals return from travel: [Assignment: organization-defined security requirements].",
  "03.05": "Identification and Authentication",
  "03.05.01.a": "Uniquely identify and authenticate system users, and associate that unique identification with processes acting on behalf of those users.",
  "03.05.01.b": "Re-authenticate users when [Assignment: organization-defined circumstances or situations requiring re-authentication].",
  "03.05.02": "Uniquely identify and authenticate [Assignment: organization-defined devices or types of devices] before establishing a system connection.",
  "03.05.03": "Implement multi-factor authentication for access to privileged and non-privileged accounts.",
  "03.05.04": "Implement replay-resistant authentication mechanisms for access to privileged and non-privileged accounts.",
  "03.05.05.a": "Receive authorization from organizational personnel or roles to assign an individual, group, role, service, or device identifier.",
  "03.05.05.b": "Select and assign an identifier that identifies an individual, group, role, service, or device.",
  "03.05.05.c": "Prevent the reuse of identifiers for [Assignment: organization-defined time period].",
  "03.05.05.d": "Manage individual identifiers by uniquely identifying each individual as [Assignment: organization-defined characteristic identifying individual status].",
  "03.05.07.a": "Maintain a list of commonly-used, expected, or compromised passwords, and update the list [Assignment: organization-defined frequency] and when organizational passwords are suspected to have been compromised.",
  "03.05.07.b": "Verify that passwords are not found on the list of commonly used, expected, or compromised passwords when users create or update passwords.",
  "03.05.07.c": "Transmit passwords only over cryptographically protected channels.",
  "03.05.07.d": "Store passwords in a cryptographically protected form.",
  "03.05.07.e": "Select a new password upon first use after account recovery.",
  "03.05.07.f": "Enforce the following composition and complexity rules for passwords: [Assignment: organization-defined composition and complexity rules].",
  "03.05.11": "Obscure feedback of authentication information during the authentication process.",
  "03.05.12.a": "Verify the identity of the individual, group, role, service, or device receiving the authenticator as part of the initial authenticator distribution.",
  "03.05.12.b": "Establish initial authenticator content for any authenticators issued by the organization.",
  "03.05.12.c": "Establish and implement administrative procedures for initial authenticator distribution; for lost, compromised, or damaged authenticators; and for revoking authenticators.",
  "03.05.12.d": "Change default authenticators at first use.",
  "03.05.12.e": "Change or refresh authenticators [Assignment: organization-defined frequency] or when the following events occur: [Assignment: organization-defined events].",
  "03.05.12.f": "Protect authenticator content from unauthorized disclosure and modification.",
  "03.06": "Incident Response",
  "03.06.01": "Implement an incident-handling capability that is consistent with the incident response plan and includes preparation, detection and analysis, containment, eradication, and recovery.",
  "03.06.02.a": "Track and document system security incidents.",
  "03.06.02.b": "Report suspected incidents to the organizational incident response capability within [Assignment: organization-defined time period].",
  "03.06.02.c": "Report incident information to [Assignment: organization-defined authorities].",
  "03.06.02.d": "Provide an incident response support resource that offers advice and assistance to system users on handling and reporting incidents.",
  "03.06.03": "Test the effectiveness of the incident response capability [Assignment: organization-defined frequency].",
  "03.06.04.a": "Provide incident response training to system users consistent with assigned roles and responsibilities:",
  "03.06.04.a.01": "Within [Assignment: organization-defined time period] of assuming an incident response role or responsibility or acquiring system access,",
  "03.06.04.a.02": "When required by system changes, and",
  "03.06.04.a.03": "[Assignment: organization-defined frequency] thereafter.",
  "03.06.04.b": "Review and update incident response training content [Assignment: organization-defined frequency] and following [Assignment: organization-defined events].",
  "03.06.05.a": "Develop an incident response plan that:",
  "03.06.05.a.01": "Provides the organization with a roadmap for implementing its incident response capability,",
  "03.06.05.a.02": "Describes the structure and organization of the incident response capability,",
  "03.06.05.a.03": "Provides a high-level approach for how the incident response capability fits into the overall organization,",
  "03.06.05.a.04": "Defines reportable incidents,",
  "03.06.05.a.05": "Addresses the sharing of incident information, and",
  "03.06.05.a.06": "Designates responsibilities to organizational entities, personnel, or roles.",
  "03.06.05.b": "Distribute copies of the incident response plan to designated incident response personnel (identified by name and/or by role) and organizational elements.",
  "03.06.05.c": "Update the incident response plan to address system and organizational changes or problems encountered during plan implementation, execution, or testing.",
  "03.06.05.d": "Protect the incident response plan from unauthorized disclosure.",
  "03.07": "Maintenance",
  "03.07.04.a": "Approve, control, and monitor the use of system maintenance tools.",
  "03.07.04.b": "Check media with diagnostic and test programs for malicious code before it is used in the system.",
  "03.07.04.c": "Prevent the removal of system maintenance equipment containing CUI by verifying that there is no CUI on the equipment, sanitizing or destroying the equipment, or retaining the equipment within the facility.",
  "03.07.05.a": "Approve and monitor nonlocal maintenance and diagnostic activities.",
  "03.07.05.b": "Implement multi-factor authentication and replay resistance in the establishment of nonlocal maintenance and diagnostic sessions.",
  "03.07.05.c": "Terminate session and network connections when nonlocal maintenance is completed.",
  "03.07.06.a": "Establish a process for maintenance personnel authorization.",
  "03.07.06.b": "Maintain a list of authorized maintenance organizations or personnel.",
  "03.07.06.c": "Verify that non-escorted personnel who perform maintenance on the system possess the required access authorizations.",
  "03.07.06.d": "Designate organizational personnel with required access authorizations and technical competence to supervise the maintenance activities of personnel who do not possess the required access authorizations.",
  "03.08": "Media Protection",
  "03.08.01": "Physically control and securely store system media that contain CUI.",
  "03.08.02": "Restrict access to CUI on system media to authorized personnel or roles.",
  "03.08.03": "Sanitize system media that contain CUI prior to disposal, release out of organizational control, or release for reuse.",
  "03.08.04": "Mark system media that contain CUI to indicate distribution limitations, handling caveats, and applicable CUI markings.",
  "03.08.05.a": "Protect and control system media that contain CUI during transport outside of controlled areas.",
  "03.08.05.b": "Maintain accountability of system media that contain CUI during transport outside of controlled areas.",
  "03.08.05.c": "Document activities associated with the transport of system media that contain CUI.",
  "03.08.07.a": "Restrict or prohibit the use of [Assignment: organization-defined types of system media].",
  "03.08.07.b": "Prohibit the use of removable system media without an identifiable owner.",
  "03.08.09.a": "Protect the confidentiality of backup information.",
  "03.08.09.b": "Implement cryptographic mechanisms to prevent the unauthorized disclosure of CUI at backup storage locations.",
  "03.09": "Personnel Security",
  "03.09.01.a": "Screen individuals prior to authorizing access to the system.",
  "03.09.01.b": "Rescreen individuals in accordance with [Assignment: organization-defined conditions requiring rescreening].",
  "03.09.02.a": "When individual employment is terminated:",
  "03.09.02.a.01": "Disable system access within [Assignment: organization-defined time period],",
  "03.09.02.a.02": "Terminate or revoke authenticators and credentials associated with the individual, and",
  "03.09.02.a.03": "Retrieve security-related system property.",
  "03.09.02.b": "When individuals are reassigned or transferred to other positions in the organization:",
  "03.09.02.b.01": "Review and confirm the ongoing operational need for current logical and physical access authorizations to the system and facility, and",
  "03.09.02.b.02": "Modify access authorization to correspond with any changes in operational need.",
  "03.10": "Physical Protection",
  "03.10.01.a": "Develop, approve, and maintain a list of individuals with authorized access to the facility where the system resides.",
  "03.10.01.b": "Issue authorization credentials for facility access.",
  "03.10.01.c": "Review the facility access list [Assignment: organization-defined frequency].",
  "03.10.01.d": "Remove individuals from the facility access list when access is no longer required.",
  "03.10.02.a": "Monitor physical access to the facility where the system resides to detect and respond to physical security incidents.",
  "03.10.02.b": "Review physical access logs [Assignment: organization-defined frequency] and upon occurrence of [Assignment: organization-defined events or potential indications of events].",
  "03.10.06.a": "Determine alternate work sites allowed for use by employees.",
  "03.10.06.b": "Employ the following security requirements at alternate work sites: [Assignment: organization-defined security requirements].",
  "03.10.07.a": "Enforce physical access authorizations at entry and exit points to the facility where the system resides by:",
  "03.10.07.a.01": "Verifying individual physical access authorizations before granting access to the facility and",
  "03.10.07.a.02": "Controlling ingress and egress with physical access control systems, devices, or guards.",
  "03.10.07.b": "Maintain physical access audit logs for entry or exit points.",
  "03.10.07.c": "Escort visitors, and control visitor activity.",
  "03.10.07.d": "Secure keys, combinations, and other physical access devices.",
  "03.10.07.e": "Control physical access to output devices to prevent unauthorized individuals from obtaining access to CUI.",
  "03.10.08": "Control physical access to system distribution and transmission lines within organizational facilities.",
  "03.11": "Risk Assessment",
  "03.11.01.a": "Assess the risk (including supply chain risk) of unauthorized disclosure resulting from the processing, storage, or transmission of CUI.",
  "03.11.01.b": "Update risk assessments [Assignment: organization-defined frequency].",
  "03.11.02.a": "Monitor and scan the system for vulnerabilities [Assignment: organization-defined frequency] and when new vulnerabilities affecting the system are identified.",
  "03.11.02.b": "Remediate system vulnerabilities within [Assignment: organization-defined response times].",
  "03.11.02.c": "Update system vulnerabilities to be scanned [Assignment: organization-defined frequency] and when new vulnerabilities are identified and reported.",
  "03.11.04": "Respond to findings from security assessments, monitoring, and audits.",
  "03.12": "Security Assessment and Monitoring",
  "03.12.01": "Assess the security requirements for the system and its environment of operation [Assignment: organization-defined frequency] to determine if the requirements have been satisfied.",
  "03.12.02.a": "Develop a plan of action and milestones for the system:",
  "03.12.02.a.01": "To document the planned remediation actions to correct weaknesses or deficiencies noted during security assessments and",
  "03.12.02.a.02": "To reduce or eliminate known system vulnerabilities.",
  "03.12.02.b": "Update the existing plan of action and milestones based on the findings from:",
  "03.12.02.b.01": "Security assessments,",
  "03.12.02.b.02": "Audits or reviews, and",
  "03.12.02.b.03": "Continuous monitoring activities.",
  "03.12.03": "Develop and implement a system-level continuous monitoring strategy that includes ongoing monitoring and security assessments.",
  "03.12.05.a": "Approve and manage the exchange of CUI between the system and other systems using [Selection (one or more): interconnection security agreements; information exchange security agreements; memoranda of understanding or agreement; service-level agreements; user agreements; non-disclosure agreements; other types of agreements].",
  "03.12.05.b": "Document interface characteristics, security requirements, and responsibilities for each system as part of the exchange agreements.",
  "03.12.05.c": "Review and update the exchange agreements [Assignment: organization-defined frequency].",
  "03.13": "System and Communications Protection",
  "03.13.01.a": "Monitor and control communications at external managed interfaces to the system and key internal managed interfaces within the system.",
  "03.13.01.b": "Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.",
  "03.13.01.c": "Connect to external systems only through managed interfaces that consist of boundary protection devices arranged in accordance with an organizational security architecture.",
  "03.13.04": "Prevent unauthorized and unintended information transfer via shared system resources.",
  "03.13.06": "Deny network communications traffic by default, and allow network communications traffic by exception.",
  "03.13.08": "Implement cryptographic mechanisms to prevent the unauthorized disclosure of CUI during transmission and while in storage.",
  "03.13.09": "Terminate the network connection associated with a communications session at the end of the session or after [Assignment: organization-defined time period] of inactivity.",
  "03.13.10": "Establish and manage cryptographic keys in the system in accordance with the following key management requirements: [Assignment: organization-defined requirements for key generation, distribution, storage, access, and destruction].",
  "03.13.11": "Implement the following types of cryptography to protect the confidentiality of CUI: [Assignment: organization-defined types of cryptography].",
  "03.13.12.a": "Prohibit the remote activation of collaborative computing devices and applications with the following exceptions: [Assignment: organization-defined exceptions where remote activation is to be allowed].",
  "03.13.12.b": "Provide an explicit indication of use to users physically present at the devices.",
  "03.13.13.a": "Define acceptable mobile code and mobile code technologies.",
  "03.13.13.b": "Authorize, monitor, and control the use of mobile code.",
  "03.13.15": "Protect the authenticity of communications sessions.",
  "03.14": "System and Information Integrity",
  "03.14.01.a": "Identify, report, and correct system flaws.",
  "03.14.01.b": "Install security-relevant software and firmware updates within [Assignment: organization-defined time period] of the release of the updates.",
  "03.14.02.a": "Implement malicious code protection mechanisms at system entry and exit points to detect and eradicate malicious code.",
  "03.14.02.b": "Update malicious code protection mechanisms as new releases are available in accordance with configuration management policies and procedures.",
  "03.14.02.c": "Configure malicious code protection mechanisms to:",
  "03.14.02.c.01": "Perform scans of the system [Assignment: organization-defined frequency] and real-time scans of files from external sources at endpoints or system entry and exit points as the files are downloaded, opened, or executed; and",
  "03.14.02.c.02": "Block malicious code, quarantine malicious code, or take other mitigation actions in response to malicious code detection.",
  "03.14.03.a": "Receive system security alerts, advisories, and directives from external organizations on an ongoing basis.",
  "03.14.03.b": "Generate and disseminate internal system security alerts, advisories, and directives, as necessary.",
  "03.14.06.a": "Monitor the system to detect:",
  "03.14.06.a.01": "Attacks and indicators of potential attacks and",
  "03.14.06.a.02": "Unauthorized connections.",
  "03.14.06.b": "Identify unauthorized use of the system.",
  "03.14.06.c": "Monitor inbound and outbound communications traffic to detect unusual or unauthorized activities or conditions.",
  "03.14.08": "Manage and retain CUI within the system and CUI output from the system in accordance with applicable laws, Executive Orders, directives, regulations, policies, standards, guidelines, and operational requirements.",
  "03.15": "Planning",
  "03.15.01.a": "Develop, document, and disseminate to organizational personnel or roles the policies and procedures needed to satisfy the security requirements for the protection of CUI.",
  "03.15.01.b": "Review and update policies and procedures [Assignment: organization-defined frequency].",
  "03.15.02.a": "Develop a system security plan that:",
  "03.15.02.a.01": "Defines the constituent system components;",
  "03.15.02.a.02": "Identifies the information types processed, stored, and transmitted by the system;",
  "03.15.02.a.03": "Describes specific threats to the system that are of concern to the organization;",
  "03.15.02.a.04": "Describes the operational environment for the system and any dependencies on or connections to other systems or system components;",
  "03.15.02.a.05": "Provides an overview of the security requirements for the system;",
  "03.15.02.a.06": "Describes the safeguards in place or planned for meeting the security requirements;",
  "03.15.02.a.07": "Identifies individuals that fulfill system roles and responsibilities; and",
  "03.15.02.a.08": "Includes other relevant information necessary for the protection of CUI.",
  "03.15.02.b": "Review and update the system security plan [Assignment: organization-defined frequency].",
  "03.15.02.c": "Protect the system security plan from unauthorized disclosure.",
  "03.15.03.a": "Establish rules that describe the responsibilities and expected behavior for system usage and protecting CUI.",
  "03.15.03.b": "Provide rules to individuals who require access to the system.",
  "03.15.03.c": "Receive a documented acknowledgement from individuals indicating that they have read, understand, and agree to abide by the rules of behavior before authorizing access to CUI and the system.",
  "03.15.03.d": "Review and update the rules of behavior [Assignment: organization-defined frequency].",
  "03.16": "System and Services Acquisition",
  "03.16.01": "Apply the following systems security engineering principles to the development or modification of the system and system components: [Assignment: organization-defined systems security engineering principles].",
  "03.16.02.a": "Replace system components when support for the components is no longer available from the developer, vendor, or manufacturer.",
  "03.16.02.b": "Provide options for risk mitigation or alternative sources for continued support for unsupported components that cannot be replaced.",
  "03.16.03.a": "Require the providers of external system services used for the processing, storage, or transmission of CUI to comply with the following security requirements: [Assignment: organization-defined security requirements].",
  "03.16.03.b": "Define and document user roles and responsibilities with regard to external system services, including shared responsibilities with external service providers.",
  "03.16.03.c": "Implement processes, methods, and techniques to monitor security requirement compliance by external service providers on an ongoing basis.",
  "03.17": "Supply Chain Risk Management",
  "03.17.01.a": "Develop a plan for managing supply chain risks associated with the research and development, design, manufacturing, acquisition, delivery, integration, operations, maintenance, and disposal of the system, system components, or system services.",
  "03.17.01.b": "Review and update the supply chain risk management plan [Assignment: organization-defined frequency].",
  "03.17.01.c": "Protect the supply chain risk management plan from unauthorized disclosure.",
  "03.17.02": "Develop and implement acquisition strategies, contract tools, and procurement methods to identify, protect against, and mitigate supply chain risks.",
  "03.17.03.a": "Establish a process for identifying and addressing weaknesses or deficiencies in the supply chain elements and processes.",
  "03.17.03.b": "Enforce the following security requirements to protect against supply chain risks to the system, system components, or system services and to limit the harm or consequences from supply chain-related events: [Assignment: organization-defined security requirements].",
};

/**
 * framework_key -> lookup for its section and reference IDs.
 *
 * FedRAMP baselines are SP 800-53 controls under a GSA/OMB wrapper and cite the
 * identical IDs, so they share the table.
 */
export const FRAMEWORK_SECTION_TEXT: Record<string, Record<string, string>> = {
  'nist-800-53-r5': NIST_800_53,
  'fedramp-r5': NIST_800_53,
  'nist-800-171-r3': NIST_800_171,
};

/** Look up one section or ref ID. Returns null when the framework has no source. */
export function sectionText(frameworkKey: string, id: string): string | null {
  return FRAMEWORK_SECTION_TEXT[frameworkKey]?.[id] ?? null;
}
